# Generated by Django 3.2.6 on 2021-08-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainBooks', '0003_auto_20210814_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainBooks.books')),
            ],
        ),
    ]
