# Generated by Django 3.2.6 on 2021-08-26 21:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя автора')),
                ('second_name', models.CharField(max_length=20, verbose_name='Фамилия автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название книги')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('book', models.FileField(blank=True, upload_to='book/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'fb2', 'mobi', 'epab', 'djvu'))], verbose_name='Загрузить книгу')),
                ('autors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainBooks.autor', verbose_name='Автор')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainBooks.categories', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
