# Generated by Django 3.2.6 on 2021-08-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя автора')),
                ('second_name', models.CharField(max_length=20, verbose_name='Фамилия автора')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название книги')),
                ('autors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainBooks.autor', verbose_name='Автор')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainBooks.categories', verbose_name='Жанр')),
            ],
        ),
    ]
