# Generated by Django 3.2.6 on 2021-08-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainBooks', '0002_auto_20210814_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='categor',
        ),
    ]
